name: heladeria
description: Una app de ventas multidimensionales para masterizar Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0 # taller_3_poo_e_introduccion_a_stateless_y_stateful_widgets

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  text_responsive: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true